### ISSUE TITLE
no properties or views showing for accounts after the 189th

### ISSUE THREAD

**Issue by olets** [dukt/analytics#10]
### Description

Hi! This plugin looks great. I'm running into an issue where no properties or views are showing up for the account I'm interested in. Figured out this is true for _all_ accounts after the 189th.

I understand the casual user won't run into this, but the company GA account this is on has several hundred accounts and grows steadily.

Do you think this is a plugin bug? Or maybe a GA API bug?

### Steps to reproduce

1. Have a GA account with more than 189 accounts
2. Connect the plugin to that GA account, and try to create a view for an account further down in the accounts' dropdown than position 189
3. No views or properties will be available

### Additional info

- Plugin version: 4.0.5 (unregistered)
- Craft version: 3.0.29
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions:

a bunch. these are the ones that show in the System Report

```
Advanced Url Field	1.0.0
Amazon S3	1.0.8
Asset Rev	6.0.1
Control Panel Nav	2.0.8
Cookies	1.1.10
CP Field Inspect	1.0.5
Dashboard Begone	1.0.1
Element Map	1.2.1
Expanded Singles	1.0.5
Field Manager	2.0.4
Flat Categories	2.0.0
Image Resizer	2.0.4
Inventory	2.0.2
Matrix Colors	2.0.1
Redactor	2.1.6
Redirect plugin for Craft 3	1.0.18
Super Table	2.0.11
Twig Perversion	2.0.6
Video Embedder	1.1.0
```

**Comment by benjamindavid** [comment]
Hey @olets, I'm thinking you might have reached a limit where the plugin only fetches the first 1000 rows for accounts, properties, and views. You probably have more properties and views than accounts, which can explain why it starts failing at some random account.

These requests will be improved to work with an unlimited number of rows.

Thanks, @olets!
