### ISSUE TITLE
migration to craft 3

### ISSUE THREAD

**Issue by krizzzly** [dukt/analytics#15]
### Steps to reproduce

1. with the latest craft 2 all plugins on the latest version
2. upgrade to craft 3
3. when installing the plugins the plugins wants to run migrations

The plugin settings are not in plugins table anymore, so we get an error here.

yii\base\ErrorException: Undefined index: settings

Migration: dukt\analytics\migrations\m180529_125418_info

Output:

> create table {{%analytics_info}} ... done (time: 0.009s)
Exception: Undefined index: settings (/www/rheumaliga3.test/vendor/dukt/analytics/src/migrations/m180529_125418_info.php:60)
#0 /www/rheumaliga3.test/vendor/craftcms/cms/src/web/ErrorHandler.php(81): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/www/rheumaliga...', 60)
#1 /www/rheumaliga3.test/vendor/dukt/analytics/src/migrations/m180529_125418_info.php(60): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/www/rheumaliga...', 60, Array)
#2 /www/rheumaliga3.test/vendor/dukt/analytics/src/migrations/m180529_125418_info.php(22): dukt\analytics\migrations\m180529_125418_info->insertDefaultData()
#3 /www/rheumaliga3.test/vendor/craftcms/cms/src/db/Migration.php(56): dukt\analytics\migrations\m180529_125418_info->safeUp()
#4 /www/rheumaliga3.test/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#5 /www/rheumaliga3.test/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(dukt\analytics\migrations\m180529_125418_info))
#6 /www/rheumaliga3.test/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#7 /www/rheumaliga3.test/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
#8 /www/rheumaliga3.test/vendor/craftcms/cms/src/controllers/UpdaterController.php(209): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#9 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#10 /www/rheumaliga3.test/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /www/rheumaliga3.test/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /www/rheumaliga3.test/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrate', Array)
#13 /www/rheumaliga3.test/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#14 /www/rheumaliga3.test/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('updater/migrate', Array)
#15 /www/rheumaliga3.test/vendor/craftcms/cms/src/web/Application.php(687): craft\web\Application->runAction('updater/migrate')
#16 /www/rheumaliga3.test/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#17 /www/rheumaliga3.test/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /www/rheumaliga3.test/web/index.php(21): yii\base\Application->run()
#19 {main}

### Additional info

- Plugin version: 
- Craft version: 3.1.27
- PHP version: 7.2.10
- Database driver & version: mysql
- Plugins & versions:

**Comment by icreatestuff** [comment]
I'm I think running into basically the same error here (also upgrading from latest version of Craft 2 to Craft 3) but the migration file throwing up the problem is 'm161021_000001_force_connect' instead.

```
yii\base\ErrorException: Undefined index: settings

Migration: dukt\analytics\migrations\m161021_000001_force_connect

Output:

Exception: Undefined index: settings (/Users/matthewjones/Sites/trent-vineyard-2020/vendor/dukt/analytics/src/migrations/m161021_000001_force_connect.php:29)
#0 /Users/matthewjones/Sites/trent-vineyard-2020/vendor/craftcms/cms/src/web/ErrorHandler.php(74): craft\web\ErrorHandler->handleError()
#1 /Users/matthewjones/Sites/trent-vineyard-2020/vendor/dukt/analytics/src/migrations/m161021_000001_force_connect.php(29): craft\web\ErrorHandler->handleError()
#2 /Users/matthewjones/Sites/trent-vineyard-2020/vendor/craftcms/cms/src/db/Migration.php(52): dukt\analytics\migrations\m161021_000001_force_connect->safeUp()
#3 /Users/matthewjones/Sites/trent-vineyard-2020/vendor/craftcms/cms/src/db/MigrationManager.php(233): dukt\analytics\migrations\m161021_000001_force_connect->up()
#4 /Users/matthewjones/Sites/trent-vineyard-2020/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp()
#5 /Users/matthewjones/Sites/trent-vineyard-2020/vendor/craftcms/cms/src/services/Updates.php(233): craft\db\MigrationManager->up()
#6 /Users/matthewjones/Sites/trent-vineyard-2020/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations()
#7 /Users/matthewjones/Sites/trent-vineyard-2020/vendor/craftcms/cms/src/controllers/pluginstore/InstallController.php(118): craft\controllers\pluginstore\InstallController->runMigrations()
#8 /Users/matthewjones/Sites/trent-vineyard-2020/vendor/yiisoft/yii2/base/InlineAction.php(57): craft\controllers\pluginstore\InstallController->actionMigrate()
#9 /Users/matthewjones/Sites/trent-vineyard-2020/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/Users/matthewjones/Sites/trent-vineyard-2020/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#10 /Users/matthewjones/Sites/trent-vineyard-2020/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#11 /Users/matthewjones/Sites/trent-vineyard-2020/vendor/craftcms/cms/src/web/Controller.php(178): craft\controllers\pluginstore\InstallController->runAction()
#12 /Users/matthewjones/Sites/trent-vineyard-2020/vendor/yiisoft/yii2/base/Module.php(528): craft\controllers\pluginstore\InstallController->runAction()
#13 /Users/matthewjones/Sites/trent-vineyard-2020/vendor/craftcms/cms/src/web/Application.php(291): craft\web\Application->runAction()
#14 /Users/matthewjones/Sites/trent-vineyard-2020/vendor/craftcms/cms/src/web/Application.php(646): craft\web\Application->runAction()
#15 /Users/matthewjones/Sites/trent-vineyard-2020/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic()
#16 /Users/matthewjones/Sites/trent-vineyard-2020/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#17 /Users/matthewjones/Sites/trent-vineyard-2020/web/index.php(24): craft\web\Application->run()
#18 {main}
```
