### ISSUE TITLE
Multiple User Widgets use the same X axis labels even if Period is different

### ISSUE THREAD

**Issue by sm9** [dukt/analytics#16]
### Description
Just noticed that when two of the same Analytics widgets are on the dashboard, using different Periods (Users this Week, and Users this Year), the X axis labels on both widgets will change to the last scale that was saved for either widget. You may need to re-load the page to see this.

So in this screenshot, the Year view is showing Days on the X axis instead of Months: https://www.dropbox.com/s/ew95912xb1gtsu1/Screenshot%202019-05-23%2012.59.22.png?dl=0

### Additional info

- Plugin version: 4.0.7
- Craft version: Craft Pro 3.1.25
- PHP version: 7.1.28

**Comment by benjamindavid** [comment]
This issue has been identified and will be fixed for the next version. Thanks!
