### ISSUE TITLE
Settings dropdown are masked by other widgets

### ISSUE THREAD

**Issue by engram-design** [dukt/analytics#28]
### Description
As per the below screenshot.

![Screen Shot 2020-08-06 at 12 10 13 pm](https://user-images.githubusercontent.com/1221575/89482725-d6389c80-d7dd-11ea-9ceb-2b8cffbba4fe.png)

### Additional info
- Plugin version: 4.0.10
- Craft version: 3.4.23
- PHP version: 7.2

**Comment by benjamindavid** [comment]
Probably something that should be solved at the Craft level. Since all widgets have an absolute position, their order in the DOM determines the overlapping (last element above the previous ones).

**Comment by engram-design** [comment]
Yeah I figured, I'll submit an issue there. Kind of a hard one to fix though...
