### ISSUE TITLE
All reports outside of Active Users return "an error occurred"

### ISSUE THREAD

**Issue by amphibian** [dukt/analytics#34]
Craft CMS 3.6.7
Dukt Analytics 4.0.11

While the "Active Users" widget seems to be working, every variety of "Analytics Report" widget simple returns "an error occurred" when saved/viewed.

I made a fresh Google API account and double-checked all my eyes, tried different account authorizations - all return the same issue.

Note that these are all Google Analytics v3 accounts - they have not been upgraded to v4, which I'm sure would be a problem had they been.

**Comment by benjamindavid** [comment]
Thanks for reporting this bug. Analytics was having issues because Craft 3.6 dropped some D3 format definitions that were used in the widget charts. The issue should be fixed in [Analytics 4.0.12](https://github.com/dukt/analytics/blob/master/CHANGELOG.md#4012---2021-03-04).
