### ISSUE TITLE
Oauth Tokens Expiring

### ISSUE THREAD

**Issue by jonlongnecker** [dukt/analytics#4]
I have 3 Analytics licenses and all 3 sites have had their Google token expire yesterday. So none of my analytics items are working. I tried to reconnect one of them only to have the token show an expiration of tomorrow. Obviously I don't want to have to reconnect to Google every day. 

What's going on? Never had a problem until March 15th of 2018.

Jonathan

**Comment by jonlongnecker** [comment]
After reconnecting Analytics on all 3 sites, things worked for a few hours, and now I'm getting Invalid Credentials on all reports again. Could this be an issue on Google's side?

**Comment by johnfmorton** [comment]
I'm having the same issue. I can fix it and it's broken again after a short period.

http://share.jmx2.com/QFU6T

Craft CMS 2.6.3012
Analytics 3.4.6

**Comment by theskyfloor** [comment]
Seems to be universal!

**Comment by jeremysanchez** [comment]
Same here. Every time I reconnect I get an token with an End of Life within just a few hours.

**Comment by ldstevens** [comment]
Same issue here -- the oauth token that's being saved expires in 60 minutes. Not sure why the refresh token is no longer used. I assume something changed on the API end, but I can't find any discussions about it online. 

I tried some naive attempts at fixing it (forcing offline access in the API call for the refresh token & upgrading the API client to the latest version, which broke the plugin settings screen) but no luck. Would love to get a fix 🙏🏻

**Comment by engram-design** [comment]
Hate to chime in here with another 'me too', but wondering if its a Google thing? Will look into it to see what I find, might be just an OAuth thing.

**Comment by ldstevens** [comment]
@engram-design Yeah some of the included client libraries are quite old so I wondered if something was quietly deprecated on Google's end that led to this issue arising. Total guess though; could be a red herring. I didn't have any luck with a straight vendor/1.0.0/google/apiclient swap either. Would love to hear if you get anywhere though :)

**Comment by engram-design** [comment]
@ldstevens I'm just testing something now.

In the OAuth plugin itself, swap `"dukt/oauth2-google": "~1.0",` with `"league/oauth2-google": "~1.0",` and do a composer update. When trying to reconnect again, it actually popped up with an error (redirected back to Craft) saying that the Google+ API needed to be enabled.

Again, just testing for the moment, but worth a shot..

**Comment by engram-design** [comment]
@ldstevens Want to give this PR a go? https://github.com/dukt/oauth2-google/pull/1

Just edit the composer.json in `oauth/vendor/dukt/oauth2-google/`, then run a `composer update` from the main `oauth` folder.

**Comment by ldstevens** [comment]
@engram-design Ah well spotted! Did that work for you? No dice here unfortunately - ran the composer updates (after editing json), got the latest version, checked the URL as per that PR you spotted, but not getting refresh tokens it seems.

**Comment by engram-design** [comment]
Hmmm, yeah it’s been. Working all day for me. Didn’t even need to reconnect either as it just started working. I was also using the latest master if that helps? I can drop you a zip (or fork)

**Comment by ldstevens** [comment]
Oh cool, that's interesting. I'll wait and see what happens with the current token. Good to know it's working for you - thanks for the tip! :)

**Comment by engram-design** [comment]
@ldstevens Might be worth having a shot at https://github.com/engram-design/oauth

Do note that there's a new version of OAuth 2.1.2 - https://github.com/dukt/oauth

**Comment by ldstevens** [comment]
@engram-design Ah good point, cheers for the links to your fork (& awesome that you forked it), I've uploaded that and will see if it helps. The 
![token](https://user-images.githubusercontent.com/6646445/37641784-21281d14-2c6f-11e8-92bb-d872417449c8.png) still says +1 hr ahead GMT so we'll see.

**Comment by ldstevens** [comment]
Woo, the token is updating! Thanks Josh :)

**Comment by jonlongnecker** [comment]
Anyone else's just magically working again without doing anything?

**Comment by theskyfloor** [comment]
Yep! Fixed by itself over here.

**Comment by johnfmorton** [comment]
Same for me too. @benjamindavid worked magic. (Or was that just Google fixing things behind the scenes?)

**Comment by benjamindavid** [comment]
Fixed since OAuth 2.1.2. Thanks!
