### ISSUE TITLE
Error when saving a new view

### ISSUE THREAD

**Issue by limesquare-nl** [dukt/analytics#7]
### Description

Error when saving a new view:

Cannot use object of type stdClass as array

/home/forge/winky.nl/vendor/dukt/analytics/src/controllers/SettingsController.php line 284

In our development environment it works. The same google accounts are used. Maybe it is something with the PHP version. On our development environment we running 7.1 en on production 7.2

### Steps to reproduce

1. Connect google account
2. Save a new view

### Additional info

- Plugin version: 4.0.0-beta.3
- Craft version: 3.08
- PHP version: 7.2.0
- Database driver & version: MySQL 5.7.22

**Comment by benjamindavid** [comment]
Thanks @limesquare-nl!
