### ISSUE TITLE
PHP 7.2 Error

### ISSUE THREAD

**Issue by outline4** [dukt/analytics#8]
### Description

Internal Server Error
count() [function.count.php]: Parameter must be an array or an object that implements Countable

### Steps to reproduce

I've updated my server to PHP 7.2. 
Now, the dashboard widgets all display an internal error.  
When I try to go into the plugin's settings the above error displays.

### Additional info

- Plugin version: 3.4.7
- Craft version: 2.7.2
- PHP version: 7.2.8

**Comment by benjamindavid** [comment]
Hey @outline4, I haven't been able to reproduce using PHP 7.2.8. Do the logs tell you a little more about where the error comes from?

**Comment by benjamindavid** [comment]
Closing this, feel free to reopen if you are still getting issues.

**Comment by jamiewade** [comment]
Hey @benjamindavid, I am also getting this exact error:

```
PHP warning
count(): Parameter must be an array or an object that implements Countable
```

`\craft\plugins\analytics\vendor\1.0.0\guzzlehttp\guzzle\src\Handler\CurlFactory.php(67)`

```
public function release(EasyHandle $easy)
63     {
64         $resource = $easy->handle;
65         unset($easy->handle);
66 
67         if (count($this->handles) >= $this->maxHandles) {
68             curl_close($resource);
69         } else {
```

### Additional info
- Plugin version: 3.4.7
- Craft version: 2.7.8
- PHP version: 7.2.10

Let me know if you need anything else!
