### ISSUE TITLE
Option to limit the number of results displayed in a List widget

### ISSUE THREAD

**Issue by brettburwell** [dukt/analytics#9]
When configuring dashboard widgets (specifically the list chart) it'd be nifty if you could limit the total number of results / data points returned to avoid overly long lists of information. 

For example, the "Pageviews" widget currently returns the top 50 results (when using `Chart: List`, `Dimension: Page`, and `Metric: Pageviews` settings). It'd be nice to have the option to limit that to a smaller number, if possible.

**Comment by benjamindavid** [comment]
@brettburwell I didn't end up adding a “Limit” option but I brought prev/next pagination buttons and the list should now show 10 items per page. Thanks for the feedback!

**Comment by brettburwell** [comment]
Nice! I just updated and it looks/works great. Pagination is even better than truncating the results. Thanks for the quick and awesome fix @benjamindavid. 

p.s. I still think about our epic Jenga game at Peers in Florida. I hope life is treating you well, sir!

**Comment by benjamindavid** [comment]
@brettburwell Oh man, that game was [epic](https://www.dropbox.com/s/yrrtsc2utyflsrr/jenga.jpg?dl=0)! Good memories :) Life is great, I hope it's the same for you!
